example = {
   "textures":[
      {
         "name":"balcony_1k.hdr",
         "full_path":"/home/gaboss/blends/wall/textures/balcony_1k.hdr"
      },
      {
         "name":"branch_branch_BaseColor.png",
         "full_path":"/home/gaboss/blends/wall/textures/branch_branch_BaseColor.png"
      },
      {
         "name":"branch_branch_Metallic.png",
         "full_path":"/home/gaboss/blends/wall/textures/branch_branch_Metallic.png"
      },
      {
         "name":"branch_branch_Normal.png",
         "full_path":"/home/gaboss/blends/wall/textures/branch_branch_Normal.png"
      },
      {
         "name":"branch_branch_Roughness.png",
         "full_path":"/home/gaboss/blends/wall/textures/branch_branch_Roughness.png"
      },
      {
         "name":"button1_button_BaseColor.png",
         "full_path":"/home/gaboss/blends/wall/textures/button1_button_BaseColor.png"
      },
      {
         "name":"button1_button_Metallic.png",
         "full_path":"/home/gaboss/blends/wall/textures/button1_button_Metallic.png"
      },
      {
         "name":"button1_button_Roughness.png",
         "full_path":"/home/gaboss/blends/wall/textures/button1_button_Roughness.png"
      },
      {
         "name":"copper_Base_Color.png",
         "full_path":"/home/gaboss/blends/wall/textures/copper_Base_Color.png"
      },
      {
         "name":"copper_Metallic.png",
         "full_path":"/home/gaboss/blends/wall/textures/copper_Metallic.png"
      },
      {
         "name":"copper_Normal_DirectX.png",
         "full_path":"/home/gaboss/blends/wall/textures/copper_Normal_DirectX.png"
      },
      {
         "name":"copper_Roughness.png",
         "full_path":"/home/gaboss/blends/wall/textures/copper_Roughness.png"
      },
      {
         "name":"doily_alpha.png",
         "full_path":"/home/gaboss/blends/wall/textures/doily_alpha.png"
      },
      {
         "name":"doily_diff.jpg",
         "full_path":"/home/gaboss/blends/wall/textures/doily_diff.jpg"
      },
      {
         "name":"doily_height.bmp",
         "full_path":"/home/gaboss/blends/wall/textures/doily_height.bmp"
      },
      {
         "name":"doily_normal.bmp",
         "full_path":"/home/gaboss/blends/wall/textures/doily_normal.bmp"
      },
      {
         "name":"forniture_Base_Color.png",
         "full_path":"/home/gaboss/blends/wall/textures/forniture_Base_Color.png"
      },
      {
         "name":"forniture_Height.png",
         "full_path":"/home/gaboss/blends/wall/textures/forniture_Height.png"
      },
      {
         "name":"forniture_Normal.png",
         "full_path":"/home/gaboss/blends/wall/textures/forniture_Normal.png"
      },
      {
         "name":"forniture_Roughness.png",
         "full_path":"/home/gaboss/blends/wall/textures/forniture_Roughness.png"
      },
      {
         "name":"IMG_20181201_132400.jpg",
         "full_path":"/home/gaboss/blends/wall/textures/IMG_20181201_132400.jpg"
      },
      {
         "name":"IMG_20181202_130711.jpg",
         "full_path":"/home/gaboss/blends/wall/textures/leaf_texture.jpg"
      },
      {
         "name":"leaf_1_alpha.png",
         "full_path":"/home/gaboss/blends/wall/textures/leaf_1_alpha.png"
      },
      {
         "name":"leaf_1_diffuseOriginal.png",
         "full_path":"/home/gaboss/blends/wall/textures/leaf_1_diffuseOriginal.png"
      },
      {
         "name":"leaf_1_normal.png",
         "full_path":"/home/gaboss/blends/wall/textures/leaf_1_normal.png"
      },
      {
         "name":"leaf_alpha.png",
         "full_path":"/home/gaboss/blends/wall/textures/leaf_alpha.png"
      },
      {
         "name":"leaf_ao.png",
         "full_path":"/home/gaboss/blends/wall/textures/leaf_ao.png"
      },
      {
         "name":"leaf_diffuseOriginal.png",
         "full_path":"/home/gaboss/blends/wall/textures/leaf_diffuseOriginal.png"
      },
      {
         "name":"leaf_metallic.png",
         "full_path":"/home/gaboss/blends/wall/textures/leaf_metallic.png"
      },
      {
         "name":"leaf_normal.png",
         "full_path":"/home/gaboss/blends/wall/textures/leaf_normal.png"
      },
      {
         "name":"light_light_BaseColor.png",
         "full_path":"/home/gaboss/blends/wall/textures/light_light_BaseColor.png"
      },
      {
         "name":"light_light_Metallic.png",
         "full_path":"/home/gaboss/blends/wall/textures/light_light_Metallic.png"
      },
      {
         "name":"light_light_Normal.png",
         "full_path":"/home/gaboss/blends/wall/textures/light_light_Normal.png"
      },
      {
         "name":"light_light_Roughness.png",
         "full_path":"/home/gaboss/blends/wall/textures/light_light_Roughness.png"
      },
      {
         "name":"wall_ao.png",
         "full_path":"/home/gaboss/blends/wall/textures/wall_ao.png"
      },
      {
         "name":"wall_diffuseOriginal.png",
         "full_path":"/home/gaboss/blends/wall/textures/wall_diffuseOriginal.png"
      },
      {
         "name":"wall_height.png",
         "full_path":"/home/gaboss/blends/wall/textures/wall_height.png"
      },
      {
         "name":"wall_normal.png",
         "full_path":"/home/gaboss/blends/wall/textures/wall_normal.png"
      }
   ],
   "scene":{
      "name":"wall.blend",
      "full_path":"/home/gaboss/blends/wall/wall.blend"
   },
   "name":"test_job",
   "frames":{
      "start":0,
      "end":1
   },
   "anim_prepass":false,
   "output_format":"jpeg",
   "priority":0,
   "sanity_check":false,
   "tile_job":true,
   "tiles":{
      "padding":10,
      "y":2,
      "x":2
   },
   "tile_padding":10
}